// ─────────────────────────────────────────────────────────────────────────
// MAP / NYC — curated dataset (lab prototype).
// Each site: category, coordinates, years active (to: null = still going),
// a one-breath blurb, and — where the MAP already has the note — a deep link.
// Coordinates are the historic addresses; a few are approximate (flagged).
// ─────────────────────────────────────────────────────────────────────────

const CATEGORIES = {
  venue:     { label: "Venues & clubs",      color: "#c44040" },
  studio:    { label: "Studios & industry",  color: "#5a7a9a" },
  scene:     { label: "Scenes & streets",    color: "#6ab86a" },
  residence: { label: "Homes & landmarks",   color: "#d4952a" },
};

const SITES = [
  // ── Greenwich Village ──
  { name: "Café Wha?", cat: "venue", lat: 40.730093, lng: -74.000570, from: 1959, to: null,
    addr: "115 MacDougal St", hood: "Greenwich Village",
    blurb: "The basement room where a just-arrived Bob Dylan played his first New York sets in 1961 — and where Jimi Hendrix held a 1966 residency as Jimmy James.",
    note: "/map/MUSIC/SCENES/Greenwich-Village-folk-scene" },
  { name: "The Gaslight Cafe", cat: "venue", lat: 40.730180, lng: -74.000510, from: 1958, to: 1971,
    addr: "116 MacDougal St", hood: "Greenwich Village",
    blurb: "Basket-house centerpiece of the folk revival; Dylan's 1962 Gaslight tapes caught the scene mid-transformation.",
    note: "/map/MUSIC/SCENES/Greenwich-Village-folk-scene" },
  { name: "Gerde's Folk City", cat: "venue", lat: 40.729680, lng: -73.995640, from: 1960, to: 1987,
    addr: "11 W 4th St", hood: "Greenwich Village",
    blurb: "Dylan's first paid New York gig — April 1961, opening for John Lee Hooker. The room where the folk revival professionalized.",
    note: "/map/MUSIC/SCENES/Greenwich-Village-folk-scene" },
  { name: "Village Vanguard", cat: "venue", lat: 40.736000, lng: -74.001660, from: 1935, to: null,
    addr: "178 7th Ave S", hood: "Greenwich Village",
    blurb: "The longest-running jazz room on earth; Coltrane, Bill Evans, and Sonny Rollins all cut canonical live records in its wedge-shaped basement." },
  { name: "The Bitter End", cat: "venue", lat: 40.727680, lng: -73.999440, from: 1961, to: null,
    addr: "147 Bleecker St", hood: "Greenwich Village",
    blurb: "Folk and singer-songwriter proving ground from the revival through the '70s troubadours." },
  { name: "Café Society", cat: "venue", lat: 40.732800, lng: -74.002600, from: 1938, to: 1948,
    addr: "1 Sheridan Sq", hood: "Greenwich Village",
    blurb: "New York's first deliberately integrated nightclub — where Billie Holiday first sang “Strange Fruit” in 1939." },
  { name: "Electric Lady Studios", cat: "studio", lat: 40.732600, lng: -73.998600, from: 1970, to: null,
    addr: "52 W 8th St", hood: "Greenwich Village",
    blurb: "The studio Hendrix built and barely lived to use; Stevie Wonder's '70s runs and Patti Smith's Horses followed." },

  // ── Downtown: Bowery, SoHo, Tribeca ──
  { name: "CBGB", cat: "venue", lat: 40.724700, lng: -73.991900, from: 1973, to: 2006,
    addr: "315 Bowery", hood: "East Village / Bowery",
    blurb: "Country, bluegrass, and blues by name; Ramones, Television, Patti Smith, Blondie, and Talking Heads in fact." },
  { name: "Max's Kansas City", cat: "venue", lat: 40.736600, lng: -73.988600, from: 1965, to: 1981,
    addr: "213 Park Ave S", hood: "Union Square",
    blurb: "Warhol's back room and proto-punk's front room — the Velvet Underground's last stand with Lou Reed, summer 1970." },
  { name: "Fillmore East", cat: "venue", lat: 40.727900, lng: -73.988200, from: 1968, to: 1971,
    addr: "105 2nd Ave", hood: "East Village",
    blurb: "Bill Graham's East Coast church of the live double-LP — the Allman Brothers recorded rock's definitive live album here in 1971." },
  { name: "The Loft (David Mancuso's)", cat: "venue", lat: 40.726800, lng: -73.996200, from: 1970, to: 1974,
    addr: "647 Broadway", hood: "NoHo",
    blurb: "Invitation-only rent parties with the best sound system in the city — the seed of disco and of every DJ culture after it." },
  { name: "Paradise Garage", cat: "venue", lat: 40.728300, lng: -74.005900, from: 1977, to: 1987,
    addr: "84 King St", hood: "SoHo / Hudson Square",
    blurb: "Larry Levan's room: the sound system as an instrument, the DJ as author — “garage” house carries its name." },
  { name: "Mudd Club", cat: "venue", lat: 40.717600, lng: -74.003100, from: 1978, to: 1983,
    addr: "77 White St", hood: "Tribeca",
    blurb: "No wave and art-punk's clubhouse — downtown's deliberately scuzzy answer to uptown disco glamour." },

  // ── Midtown: Tin Pan Alley → Brill → 52nd St ──
  { name: "Tin Pan Alley", cat: "scene", lat: 40.745800, lng: -73.989700, from: 1885, to: 1929,
    addr: "W 28th St between 5th & Broadway", hood: "NoMad",
    blurb: "The block of publishers' offices where American popular song became an industry — pluggers hammering pianos out every window.",
    note: "/map/MUSIC/GENRES/POP/Tin-Pan-Alley" },
  { name: "Brill Building", cat: "studio", lat: 40.761600, lng: -73.984200, from: 1931, to: null,
    addr: "1619 Broadway", hood: "Midtown",
    blurb: "Songwriting's vertical factory: Leiber & Stoller, Pomus & Shuman, Bacharach & David stacked floor over floor.",
    note: "/map/MUSIC/GENRES/POP/Brill-Building" },
  { name: "1650 Broadway (Aldon Music)", cat: "studio", lat: 40.762200, lng: -73.983900, from: 1958, to: 1966,
    addr: "1650 Broadway", hood: "Midtown",
    blurb: "Don Kirshner's Aldon Music — Goffin & King and Mann & Weil writing the teen-pop canon a block from the Brill itself.",
    note: "/map/MUSIC/GENRES/POP/Brill-Building" },
  { name: "52nd Street — “Swing Street”", cat: "scene", lat: 40.760900, lng: -73.977700, from: 1933, to: 1955,
    addr: "W 52nd St between 5th & 6th", hood: "Midtown",
    blurb: "One brownstone block of clubs — Onyx, Three Deuces, Famous Door — where swing went small-group and bebop went public." },
  { name: "Birdland", cat: "venue", lat: 40.762700, lng: -73.983500, from: 1949, to: 1965,
    addr: "1678 Broadway", hood: "Midtown",
    blurb: "Named for Charlie Parker, eulogized by Shearing's “Lullaby of Birdland” — bebop's flagship room." },
  { name: "Studio 54", cat: "venue", lat: 40.764900, lng: -73.983600, from: 1977, to: 1980,
    addr: "254 W 54th St", hood: "Midtown",
    blurb: "Disco's velvet-rope cathedral — thirty-three months that fixed the image of nightlife as spectacle." },
  { name: "Atlantic Records", cat: "studio", lat: 40.765900, lng: -73.981900, from: 1947, to: 1959,
    addr: "234 W 56th St", hood: "Midtown",
    blurb: "The office that became a studio after dark — desks stacked against the wall for Ray Charles and Big Joe Turner sessions." },
  { name: "Columbia 30th Street Studio", cat: "studio", lat: 40.742500, lng: -73.979800, from: 1948, to: 1981,
    addr: "207 E 30th St", hood: "Kips Bay",
    blurb: "“The Church” — a deconsecrated sanctuary with the most loved room sound in record-making; Kind of Blue was cut here in 1959." },
  { name: "Columbia Studio A", cat: "studio", lat: 40.763800, lng: -73.982400, from: 1955, to: 1970,
    addr: "799 7th Ave", hood: "Midtown",
    blurb: "Where Dylan plugged in on tape — the “Like a Rolling Stone” sessions, June 1965." },
  { name: "The Power Station", cat: "studio", lat: 40.766300, lng: -73.989500, from: 1977, to: null,
    addr: "441 W 53rd St", hood: "Hell's Kitchen",
    blurb: "Chic's home base — Rodgers & Edwards' grooves, then Bowie's Let's Dance, in a converted Con Ed substation." },
  { name: "The Hit Factory", cat: "studio", lat: 40.766000, lng: -73.987900, from: 1975, to: 2005,
    addr: "421 W 54th St", hood: "Hell's Kitchen",
    blurb: "Lennon and Ono's Double Fantasy sessions ran here in 1980 — his last recordings." },

  // ── Harlem & Uptown ──
  { name: "Apollo Theater", cat: "venue", lat: 40.810000, lng: -73.950000, from: 1934, to: null,
    addr: "253 W 125th St", hood: "Harlem",
    blurb: "Amateur Night made careers from Ella Fitzgerald (1934) onward; James Brown's 1962 live LP made the room itself famous." },
  { name: "Minton's Playhouse", cat: "venue", lat: 40.804600, lng: -73.952200, from: 1938, to: 1974,
    addr: "210 W 118th St", hood: "Harlem",
    blurb: "Bebop's laboratory — Monk in the house band, Parker and Gillespie rewriting harmony at the after-hours cutting sessions." },
  { name: "Savoy Ballroom", cat: "venue", lat: 40.817500, lng: -73.937800, from: 1926, to: 1958,
    addr: "596 Lenox Ave", hood: "Harlem",
    blurb: "The block-long, integrated “Home of Happy Feet” — birthplace of the Lindy Hop; Chick Webb's band beat Benny Goodman's here in 1937." },
  { name: "Cotton Club", cat: "venue", lat: 40.819000, lng: -73.936800, from: 1923, to: 1936,
    addr: "644 Lenox Ave", hood: "Harlem",
    blurb: "Ellington's 1927–31 residency broadcast Harlem to America — from a club whose audience was whites-only by policy." },
  { name: "Audubon Ballroom", cat: "venue", lat: 40.840000, lng: -73.940100, from: 1912, to: 1980,
    addr: "3940 Broadway", hood: "Washington Heights",
    blurb: "Uptown's grand dance hall for big bands and Latin orchestras — and the site of Malcolm X's assassination in 1965." },

  // ── The Bronx ──
  { name: "1520 Sedgwick Ave", cat: "scene", lat: 40.844700, lng: -73.927800, from: 1973, to: null,
    addr: "1520 Sedgwick Ave", hood: "Morris Heights, The Bronx",
    blurb: "August 11, 1973: DJ Kool Herc's back-to-school party in the rec room — the date hip-hop gives itself as a birthday." },
  { name: "Disco Fever", cat: "venue", lat: 40.835500, lng: -73.918200, from: 1976, to: 1986,
    addr: "167th St & Jerome Ave (approx.)", hood: "Morrisania, The Bronx",
    blurb: "The first club to put rap DJs and MCs on the marquee — hip-hop's first professional home." },

  // ── Brooklyn & Queens ──
  { name: "Marcy Houses", cat: "residence", lat: 40.697600, lng: -73.947800, from: 1969, to: null,
    addr: "Marcy Ave, Bed-Stuy", hood: "Bedford-Stuyvesant, Brooklyn",
    blurb: "The towers Jay-Z wrote into hip-hop's geography — Brooklyn's answer to the Bronx origin story." },
  { name: "226 St. James Place", cat: "residence", lat: 40.689200, lng: -73.963800, from: 1972, to: 1997,
    addr: "226 St. James Pl", hood: "Clinton Hill, Brooklyn",
    blurb: "The Notorious B.I.G.'s block — Ready to Die's whole sound-world is this stretch of Brooklyn." },
  { name: "Hollis, Queens", cat: "scene", lat: 40.713200, lng: -73.762000, from: 1980, to: 1990,
    addr: "Hollis Ave around 205th St", hood: "Hollis, Queens",
    blurb: "Run-DMC's home turf — where hip-hop put on a black hat and Adidas and conquered the suburbs from the suburbs." },
  { name: "Addisleigh Park", cat: "residence", lat: 40.696000, lng: -73.764000, from: 1935, to: 1965,
    addr: "St. Albans, Queens", hood: "St. Albans, Queens",
    blurb: "The jazz aristocracy's enclave — Count Basie, Ella Fitzgerald, Lena Horne, and later James Brown all kept houses here." },

  // ── Chelsea / misc landmarks ──
  { name: "Hotel Chelsea", cat: "residence", lat: 40.744400, lng: -73.996700, from: 1884, to: null,
    addr: "222 W 23rd St", hood: "Chelsea",
    blurb: "Dylan wrote in room 211, Cohen memorialized room 424, Patti Smith and Mapplethorpe shared its smallest room — the song-filled flophouse of record." },
  { name: "Danceteria", cat: "venue", lat: 40.741200, lng: -73.991700, from: 1979, to: 1986,
    addr: "30 W 21st St", hood: "Flatiron",
    blurb: "Four floors of post-punk, video lounges, and dance floors — Madonna's first stage, 1982." },
  { name: "Webster Hall", cat: "venue", lat: 40.731700, lng: -73.989000, from: 1886, to: null,
    addr: "125 E 11th St", hood: "East Village",
    blurb: "From anarchists' balls to RCA's 1950s live-recording hall to the rave era — the city's longest-serving big room." },
];

// Soft-area neighborhood stories (centroid + radius in meters) — a lab stand-in
// for real polygons; each would become a MAP note in the full build.
const NEIGHBORHOODS = [
  { name: "Greenwich Village", lat: 40.7308, lng: -74.0000, r: 600,
    story: "Bohemia's home office: the folk revival's coffeehouse grid in the '50s–'60s (MacDougal St above all), then Electric Lady and the singer-songwriters. The MAP's Greenwich Village folk scene note starts here.",
    note: "/map/MUSIC/SCENES/Greenwich-Village-folk-scene" },
  { name: "Harlem", lat: 40.8120, lng: -73.9450, r: 1400,
    story: "The capital of Black America's nightlife century: rent parties and stride piano, the Cotton Club and Savoy in the '20s–'30s, bebop hatching at Minton's in the '40s, the Apollo running through all of it." },
  { name: "The Brill corridor", lat: 40.7620, lng: -73.9840, r: 350,
    story: "Two office buildings a block apart — 1619 and 1650 Broadway — where professional songwriting survived rock and roll by industrializing it. Teen symphonies by the floor." },
  { name: "The Bowery / East Village", lat: 40.7260, lng: -73.9900, r: 700,
    story: "Skid row real estate met art-school ambition: the Fillmore East's rock church, then CBGB's three-chord republic, then no wave's deliberate ruins." },
  { name: "The South Bronx", lat: 40.8400, lng: -73.9230, r: 1800,
    story: "Out of the fires of the '70s: block parties, sound systems, breakbeats — hip-hop assembling itself from turntables and park jams." },
  { name: "Downtown dance underground", lat: 40.7265, lng: -74.0010, r: 800,
    story: "From Mancuso's Loft to Levan's Garage: private parties that invented the modern dance floor — community as much as genre." },
  { name: "Bed-Stuy & Clinton Hill", lat: 40.6920, lng: -73.9530, r: 1300,
    story: "Brooklyn's '90s renaissance: Biggie's corner-eye view, Jay-Z's Marcy mythology — New York rap's second borough becoming its first." },
  { name: "52nd Street", lat: 40.7609, lng: -73.9777, r: 250,
    story: "“Swing Street”: a single block of brownstone basements that compressed jazz's loudest decade into the smallest rooms." },
];

// Era chips for the timeline views.
const ERAS = [
  { name: "Tin Pan Alley",        from: 1885, to: 1929 },
  { name: "Harlem nights",        from: 1923, to: 1943 },
  { name: "Swing St & bebop",     from: 1933, to: 1955 },
  { name: "Folk Village",         from: 1947, to: 1965 },
  { name: "The Brill decade",     from: 1958, to: 1966 },
  { name: "Downtown rock",        from: 1965, to: 1975 },
  { name: "Dance underground",    from: 1970, to: 1987 },
  { name: "Punk Bowery",          from: 1973, to: 1982 },
  { name: "Hip-hop's boroughs",   from: 1973, to: 1995 },
];
