// Generated by the AtlasData emitter — every note carrying `location` frontmatter.
// Loaded by /atlas/ and merged over its curated starter set (dedupe by name).
const NOTE_SITES = [
  {
    "name": "CBGB",
    "cat": "Venues",
    "lat": 40.72528,
    "lng": -73.99194,
    "from": 1973,
    "to": 2006,
    "addr": "315 Bowery, Manhattan",
    "hood": "East Village",
    "blurb": "The Bowery bar with the two rules — original music only, haul your own gear — whose door-deal economics and stolen-then-replaced sound system built punk's founding room.",
    "note": "/map/MUSIC/PLACES/VENUES/CBGB"
  },
  {
    "name": "The Loft",
    "cat": "Venues",
    "lat": 40.72667,
    "lng": -73.99806,
    "from": 1970,
    "to": null,
    "addr": "647 Broadway, Manhattan (1970–74); thereafter wherever the party moved",
    "hood": "NoHo",
    "blurb": "David Mancuso's invitation-only rent party — the audiophile room with nothing for sale, whose legal architecture and sound-system ethic became dance music's constitution.",
    "note": "/map/MUSIC/PLACES/VENUES/The-Loft"
  }
];
