// Generated by the AtlasData emitter — every note carrying `location` frontmatter.
// Loaded by /atlas/ and merged over its curated starter set (dedupe by name).
const NOTE_SITES = [
  {
    "name": "CBGB",
    "cat": "Venues",
    "lat": 40.72528,
    "lng": -73.99194,
    "from": 1973,
    "to": 2006,
    "addr": "315 Bowery, Manhattan",
    "hood": "East Village",
    "blurb": "The Bowery bar with the two rules — original music only, haul your own gear — whose door-deal economics and stolen-then-replaced sound system built punk's founding room.",
    "note": "/map/MUSIC/PLACES/VENUES/CBGB"
  },
  {
    "name": "The Loft",
    "cat": "Venues",
    "lat": 40.72667,
    "lng": -73.99806,
    "from": 1970,
    "to": null,
    "addr": "647 Broadway, Manhattan (1970–74); thereafter wherever the party moved",
    "hood": "NoHo",
    "blurb": "David Mancuso's invitation-only rent party: no bar, no license, no closing time — the audiophile room dance music still copies.",
    "note": "/map/MUSIC/PLACES/VENUES/The-Loft"
  },
  {
    "name": "CBGB scene",
    "cat": "Scenes",
    "lat": 40.72528,
    "lng": -73.99194,
    "from": 1974,
    "to": 1980,
    "addr": "315 Bowery, Manhattan",
    "hood": "East Village",
    "blurb": "The Bowery bar whose original-music-only rule selected for writers rather than for a sound — so punk, art rock and new wave all hatched on one foot-high stage.",
    "note": "/map/MUSIC/SCENES/CBGB-scene"
  },
  {
    "name": "Greenwich Village folk scene",
    "cat": "Scenes",
    "lat": 40.73083,
    "lng": -73.9975,
    "from": 1958,
    "to": 1965,
    "addr": "Washington Square Park, Greenwich Village, Manhattan",
    "hood": "Greenwich Village",
    "blurb": "A few square blocks of lower Manhattan where five years of coffeehouse apprenticeship tied popular song to political consciousness.",
    "note": "/map/MUSIC/SCENES/Greenwich-Village-folk-scene"
  }
];
